spring.application.name=primo-progetto
server.port=8081
# Questa riga attiva il profilo DEV
spring.profiles.active=dev
# Sblocca Actuator 
management.endpoints.web.exposure.include=*
# Proprietà comuni 
app.nome=Academy App
app.versione=1.0.0